#!/usr/bin/env node

import { fileURLToPath } from 'url';
import { dirname } from 'path';
import * as path from 'path';
import { marked } from 'marked';
import yargs from 'yargs';
import { hideBin } from 'yargs/helpers';
import { getPackageName } from './lib/name.js';
import { readMarkDownFileSync, changeExtensionToHtml, writeHtmlFileSync } from './lib/file.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const { argv } = yargs(hideBin(process.argv))
  .option('name', {
    describe: 'Show the name of the CLI tool'
  })
  .option('convert', {
    describe: 'Convert a markdown file to an HTML file and export it',
    default: 'out.html'
  });

if (argv.name) {
  const name = getPackageName()
  console.log(name);
  process.exit(0);
}

const markdownStr = readMarkDownFileSync(path.resolve(__dirname, argv.convert));
const html = marked(markdownStr);
const outputPath = changeExtensionToHtml(argv.convert);

writeHtmlFileSync(path.resolve(__dirname, outputPath), html);
