#!/usr/bin/env node

const path = require('path');
const { marked } = require('marked');
const yargs = require('yargs/yargs');
const { hideBin } = require('yargs/helpers');
const { getPackageName } = require('./lib/name');
const { readMarkDownFileSync, changeExtensionToHtml, writeHtmlFileSync } = require('./lib/file');

const { argv } = yargs(hideBin(process.argv))
  .option('name', {
    describe: 'Show the name of the CLI tool'
  })
  .option('convert', {
    describe: 'Convert a markdown file to an HTML file and export it',
    default: 'out.html'
  });

if (argv.name) {
  const name = getPackageName()
  console.log(name);
  process.exit(0);
}

const markdownStr = readMarkDownFileSync(path.resolve(__dirname, argv.convert));
const html = marked(markdownStr);
const outputPath = changeExtensionToHtml(argv.convert);

writeHtmlFileSync(path.resolve(__dirname, outputPath), html);
